CRITICAL - 2022-12-20 00:00:54 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(141): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:27:26 --> syntax error, unexpected token "/", expecting "function" or "const"
in APPPATH\Models\MyFgPackingModel.php on line 466.
 1 SYSTEMPATH\Autoloader\Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Models\\MyFgPackingModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\MyFgPackingModel')
 3 APPPATH\Controllers\Fg_packing.php(13): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\MyFgPackingModel')
 4 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Fg_packing->__construct()
 5 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:30:55 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(182): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:32:58 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(118): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:38:21 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(138): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:44:05 --> CodeIgniter\Database\MySQLi\Connection::_escapeString(): Argument #1 ($str) must be of type string, null given, called in D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php on line 1248
in SYSTEMPATH\Database\MySQLi\Connection.php on line 329.
 1 SYSTEMPATH\Database\BaseConnection.php(1248): CodeIgniter\Database\MySQLi\Connection->_escapeString(null)
 2 APPPATH\Models\MyFgPackingModel.php(98): CodeIgniter\Database\BaseConnection->escapeString(null)
 3 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:54:00 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(139): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 00:55:36 --> count(): Argument #1 ($value) must be of type Countable|array, null given
in APPPATH\Models\MyFgPackingModel.php on line 122.
 1 APPPATH\Models\MyFgPackingModel.php(122): count(null)
 2 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 01:23:48 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(189): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 01:29:05 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(189): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 01:30:21 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(189): CodeIgniter\Model->__call('get_ctr_new_dr', [...])
 4 APPPATH\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 01:32:48 --> mysqli_sql_exception: Unknown column 'CTRL_GWFGPA' in 'field list' in D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php(292): mysqli->query('select CTRL_GWF...', 0)
#1 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('select CTRL_GWF...')
#2 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('select CTRL_GWF...')
#3 D:\xampp\webapps\mytestapp\app\Models\MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query('select CTRL_GWF...')
#4 D:\xampp\webapps\mytestapp\app\Models\MyDatumModel.php(75): App\Models\MyLibzDBModel->myoa_sql_exec('select CTRL_GWF...', 'URI: /mytestapp...')
#5 D:\xampp\webapps\mytestapp\app\Models\MyFgPackingModel.php(189): App\Models\MyDatumModel->get_ctr_new_dr('FG', '', 'medbroc', 'CTRL_GWFGPA')
#6 D:\xampp\webapps\mytestapp\app\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
#7 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
#8 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
#9 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\webapps\mytestapp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-12-20 01:36:31 --> mysqli_sql_exception: Unknown column 'CTRL_GWFGPA' in 'field list' in D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php(292): mysqli->query('select CTRL_GWF...', 0)
#1 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('select CTRL_GWF...')
#2 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('select CTRL_GWF...')
#3 D:\xampp\webapps\mytestapp\app\Models\MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query('select CTRL_GWF...')
#4 D:\xampp\webapps\mytestapp\app\Models\MyDatumModel.php(75): App\Models\MyLibzDBModel->myoa_sql_exec('select CTRL_GWF...', 'URI: /mytestapp...')
#5 D:\xampp\webapps\mytestapp\app\Models\MyFgPackingModel.php(189): App\Models\MyDatumModel->get_ctr_new_dr('FG', '', 'medbroc', 'CTRL_GWFGPA')
#6 D:\xampp\webapps\mytestapp\app\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
#7 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
#8 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
#9 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\webapps\mytestapp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-12-20 01:36:46 --> mysqli_sql_exception: Unknown column 'CTRL_GWFGPA' in 'field list' in D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\xampp\webapps\mytestapp\system\Database\MySQLi\Connection.php(292): mysqli->query('select CTRL_GWF...', 0)
#1 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('select CTRL_GWF...')
#2 D:\xampp\webapps\mytestapp\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('select CTRL_GWF...')
#3 D:\xampp\webapps\mytestapp\app\Models\MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query('select CTRL_GWF...')
#4 D:\xampp\webapps\mytestapp\app\Models\MyDatumModel.php(75): App\Models\MyLibzDBModel->myoa_sql_exec('select CTRL_GWF...', 'URI: /mytestapp...')
#5 D:\xampp\webapps\mytestapp\app\Models\MyFgPackingModel.php(189): App\Models\MyDatumModel->get_ctr_new_dr('FG', '', 'medbroc', 'CTRL_GWFGPA')
#6 D:\xampp\webapps\mytestapp\app\Controllers\Fg_packing.php(26): App\Models\MyFgPackingModel->fgpack_entry_save()
#7 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_save()
#8 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
#9 D:\xampp\webapps\mytestapp\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\webapps\mytestapp\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-12-20 01:58:21 --> Invalid file: mtap/fgpack/trx-fg-pack-print.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('mtap/fgpack/trx-fg-pack-print.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('mtap/fgpack/trx-fg-pack-print', [], true)
 3 APPPATH\Controllers\Fg_packing.php(44): view('mtap/fgpack/trx-fg-pack-print')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_print()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 02:03:03 --> Trying to access array offset on value of type null
in APPPATH\Views\mtap\fgpack\trx-fg-pack.php on line 57.
 1 APPPATH\Views\mtap\fgpack\trx-fg-pack.php(57): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\mtap\\fgpack\\trx-fg-pack.php', 57)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\mtap\\fgpack\\trx-fg-pack.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('mtap/fgpack/trx-fg-pack', [], true)
 5 APPPATH\Controllers\Fg_packing.php(20): view('mtap/fgpack/trx-fg-pack')
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 02:03:13 --> You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 845.
 1 SYSTEMPATH\Model.php(587): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(764): CodeIgniter\Model->builder()
 3 APPPATH\Models\MyFgPackingModel.php(904): CodeIgniter\Model->__call('random_string', [...])
 4 APPPATH\Controllers\Fg_packing.php(65): App\Models\MyFgPackingModel->download_fgpack_barcode('FG2211230000000002', '4')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_barcode_dl_proc()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-20 02:49:25 --> Invalid file: mtap/fgpack/trx-fg-pack-print.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('mtap/fgpack/trx-fg-pack-print.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('mtap/fgpack/trx-fg-pack-print', [], true)
 3 APPPATH\Controllers\Fg_packing.php(44): view('mtap/fgpack/trx-fg-pack-print')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fg_packing->fgpack_print()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fg_packing))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 23:47:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'meredorchad'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /mdevs/mytestapp/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#4 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#5 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#6 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#8 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#9 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#10 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#11 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#12 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#3 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#4 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#5 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#7 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#8 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#9 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#10 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#11 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-20 23:47:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/mtap/fgpack/trx-fg-pack.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1134): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Fg_packing.php(20): view()
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 23:49:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'meredorchad'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /mdevs/mytestapp/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#4 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#5 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#6 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#8 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#9 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#10 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#11 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#12 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#3 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#4 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#5 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#7 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#8 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#9 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#10 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#11 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-20 23:49:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/mtap/fgpack/trx-fg-pack.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1134): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Fg_packing.php(20): view()
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 23:49:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'meredorchad'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /mdevs/mytestapp/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#4 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#5 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#6 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#8 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#9 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#10 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#11 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#12 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#3 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#4 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#5 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#7 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#8 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#9 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#10 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#11 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-20 23:49:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/mtap/fgpack/trx-fg-pack.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1134): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Fg_packing.php(20): view()
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 23:49:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'meredorchad'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /mdevs/mytestapp/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#4 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#5 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#6 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#8 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#9 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#10 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#11 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#12 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#3 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#4 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#5 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#7 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#8 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#9 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#10 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#11 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-20 23:49:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/mtap/fgpack/trx-fg-pack.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1134): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Fg_packing.php(20): view()
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-20 23:49:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'meredorchad'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /mdevs/mytestapp/system/Database/MySQLi/Connection.php(171): mysqli->real_connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#4 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#5 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#6 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#8 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#9 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#10 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#11 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#12 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in /mdevs/mytestapp/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /mdevs/mytestapp/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /mdevs/mytestapp/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /mdevs/mytestapp/app/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
#3 /mdevs/mytestapp/app/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
#4 /mdevs/mytestapp/system/View/View.php(213): include('/mdevs/mytestap...')
#5 /mdevs/mytestapp/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /mdevs/mytestapp/system/Common.php(1134): CodeIgniter\View\View->render()
#7 /mdevs/mytestapp/app/Controllers/Fg_packing.php(20): view()
#8 /mdevs/mytestapp/system/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
#9 /mdevs/mytestapp/system/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
#10 /mdevs/mytestapp/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
#11 /mdevs/mytestapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-20 23:49:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/MyLibzDBModel.php(19): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Views/mtap/fgpack/trx-fg-pack.php(222): App\Models\MyLibzDBModel->myoa_sql_exec()
 4 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/mtap/fgpack/trx-fg-pack.php')
 5 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH/Common.php(1134): CodeIgniter\View\View->render()
 7 APPPATH/Controllers/Fg_packing.php(20): view()
 8 SYSTEMPATH/CodeIgniter.php(927): App\Controllers\Fg_packing->index()
 9 SYSTEMPATH/CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
